### ISSUE TITLE
超哥，这个库是不是不支持区分支持/反对两种状态？

### ISSUE THREAD

**Issue by JimChenWYU** [overtrue/laravel-vote#1]
初步看了源码，貌似只有一个状态的vote

**Comment by overtrue** [comment]
哈哈哈，还在搞，昨晚为了回家写就先提交了，从 laravel-favtorite 改过来的

**Comment by JimChenWYU** [comment]
😆 OK

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-vote @JimChenWYU  😆
