### ISSUE TITLE
During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /vendor/overtrue/laravel-vote/src/Traits/Voter.php

### ISSUE THREAD

**Issue by gitamgadtaula** [overtrue/laravel-vote#2]
Theres is an error in attachVoteStatus() Method in Voter Trait. 
`
public function attachVoteStatus(Model | Collection | Paginator | LengthAwarePaginator | array $votables): Collection | Model`

**Comment by overtrue** [comment]
PHP 8 required

**Comment by gitamgadtaula** [comment]
> PHP 8 required

Well isn't there another version of the package which will be compatible with php7.x and laravel 8.x?

**Comment by overtrue** [comment]
@gitamgadtaula you can fork and update this package to compatible with PHP 7.x
