### ISSUE TITLE
downvote count not working as expected

### ISSUE THREAD

**Issue by Chizzycute** [overtrue/laravel-vote#3]
I have created a function in my livewire components

```
public function downvote(Post $post)
{
  auth()->user()->downvote($post)
}

I noticed when I downvote a post the count increase for the upvote instead

**Comment by overtrue** [comment]
Please confirm this from the database after calling the API, because it seems impossible:

https://github.com/overtrue/laravel-vote/blob/master/src/Traits/Voter.php#L36-L49
