### ISSUE TITLE
Why total votes are returned as an absolute value?

### ISSUE THREAD

**Issue by gordanielyan** [overtrue/laravel-vote#5]
For example if there are more downvotes shouldn't it return a negative value?
https://github.com/overtrue/laravel-vote/blob/8573e50e88b9cd43ea1037948bf216bc1edaf886/src/Traits/Votable.php#L77

**Comment by overtrue** [comment]
<del>@gordanielyan I don't think so, it means "How many users voted" or "How many votes were cast in total", not "upvotes - downvotes"</del>

**Comment by gordanielyan** [comment]
@overtrue but why is it sum then?
https://github.com/overtrue/laravel-vote/blob/8573e50e88b9cd43ea1037948bf216bc1edaf886/src/Traits/Votable.php#L92

if you have 3 downvotes and one upvote it returns 2, is it right result?

**Comment by overtrue** [comment]
Sorry, I went through the source code again, you are right, this project has not been updated for too long, after just reading it carefully, I confirmed that the abs here should be redundant, it may be a problem caused by copying the code at first, I'll fix it, thanks again for your feedback.

**Comment by overtrue** [comment]
@gordanielyan https://github.com/overtrue/laravel-vote/releases/tag/3.0.2
